In [45]:
import pandas as pd
import numpy as np

In [3]:
data = "/home/asus/Machine-Learning/ml-zoomcamp-2k26/module-1/datasets/car_fuel_efficiency_2026.csv"
df = pd.read_csv(data)

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [8]:
df.shape[0]

10000

In [11]:
df['fuel_type'].nunique()

3

In [17]:
df.isnull().sum().nunique() - 1

2

In [26]:
(df.isnull().sum() > 0).sum().item()

2

In [25]:
df[df.origin == "Asia"].fuel_efficiency_mpg.max().item()

41.2

In [34]:
df.horsepower.median().item()

254.0

In [87]:
df.horsepower.isnull().sum().item()

877

In [93]:
mode = df.horsepower.mode().item()
df['horsepower'] = df['horsepower'].fillna(mode)
df.horsepower.median().item()

252.0

In [60]:
selected_cols = ['vehicle_weight', 'model_year']

filtered_df = df.loc[df.origin == "Asia", selected_cols].iloc[:7]

filtered_df

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [62]:
X = np.array(filtered_df)
XTX = X.T.dot(X)

In [63]:
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [65]:
XTX_INV = np.linalg.inv(XTX)
XTX_INV

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [71]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [76]:
w = XTX_INV.dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

In [77]:
w.sum().item()

0.36919696904925486

In [80]:
pd.__version__

'3.0.6'