In [85]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [86]:
data = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv"

In [4]:
!wget -P /home/asus/Machine-Learning/ml-zoomcamp-2k26/module_3_classification/datasets/ $data

--2026-10-11 12:01:20--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 278746 (272K) [text/plain]
Saving to: ‘/home/asus/Machine-Learning/ml-zoomcamp-2k26/module_3_classification/datasets/course_lead_scoring_2026.csv’

course_lead_scoring 100%[===================>] 272.21K  --.-KB/s    in 0.1s

2026-10-11 12:01:21 (1.84 MB/s) - ‘/home/asus/Machine-Learning/ml-zoomcamp-2k26/module_3_classification/datasets/course_lead_scoring_2026.csv’ saved [278746/278746]

In [87]:
df = pd.read_csv("/home/asus/Machine-Learning/ml-zoomcamp-2k26/module_3_classification/datasets/course_lead_scoring_2026.csv")

In [88]:
df.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

In [89]:
df.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [90]:
df.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [91]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
categorical = list(df.columns[df.dtypes == 'str'])
numerical = list(df.columns[df.dtypes != 'str'])

In [92]:
df[categorical] = df[categorical].fillna('unknown')
df[numerical] = df[numerical].fillna(0)

In [93]:
df.isnull().sum()

lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

In [94]:
df['lead_source'].unique()

<StringArray>
['organic_search', 'social_media', 'referral', 'paid_ads', 'unknown',
 'events']
Length: 6, dtype: str

In [95]:


for c in categorical:
    df[c] = df[c].str.lower().str.replace(' ', '_')
for c in categorical:
    df[c] = df[c].str.replace('unknown', 'NA')

In [96]:
df['lead_source'].unique()

<StringArray>
['organic_search', 'social_media', 'referral', 'paid_ads', 'NA', 'events']
Length: 6, dtype: str

In [97]:
df.head().T

,0,1,2,3,4
lead_source,organic_search,social_media,referral,paid_ads,referral
industry,technology,technology,retail,manufacturing,manufacturing
employment_status,employed,employed,employed,student,student
location,europe,south_america,europe,NA,north_america
annual_income,88160.0,72688.0,44697.0,0.0,24062.0
number_of_courses_viewed,3,3,3,3,4
interaction_count,4,7,4,6,5
lead_score,0.64,0.72,0.58,0.57,0.62
converted,1,1,1,0,1

In [98]:
# can see from above result that data cleaning is done... although there was nothing to clean...lol
# our target variable is "converted"

from sklearn.model_selection import train_test_split

df_full_train, df_test = train_test_split(df, test_size = 0.2, random_state = 1)
df_train, df_val = train_test_split(df_full_train, test_size = 0.25, random_state = 1)

for c in (df_train, df_val, df_test) : print(len(c))

3000
1000
1000

In [99]:
# GTR line

df_train, df_val, df_test = map(lambda df: df.reset_index(drop = True), (df_train, df_val, df_test))

In [100]:
df_train.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,paid_ads,technology,employed,asia,80198.0,5,9,0.91,1
1,paid_ads,retail,employed,asia,50548.0,2,5,0.48,0
2,NA,finance,employed,NA,76300.0,0,3,0.42,0
3,paid_ads,finance,employed,NA,80371.0,2,6,0.49,0
4,organic_search,finance,employed,asia,73567.0,2,4,0.48,1

In [101]:
y_train = df_train['converted'].values
y_val = df_val['converted'].values
y_test = df_test['converted'].values

df_train, df_val, df_test = [df.drop(columns = ['converted']) for df in (df_train, df_val, df_test)]

In [102]:
df_train.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score
0,paid_ads,technology,employed,asia,80198.0,5,9,0.91
1,paid_ads,retail,employed,asia,50548.0,2,5,0.48
2,NA,finance,employed,NA,76300.0,0,3,0.42
3,paid_ads,finance,employed,NA,80371.0,2,6,0.49
4,organic_search,finance,employed,asia,73567.0,2,4,0.48

In [103]:
df_full_train.reset_index(drop=True)

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,paid_ads,technology,student,europe,38757.0,0,0,0.15,0
1,paid_ads,healthcare,self_employed,north_america,56516.0,2,6,0.59,1
2,paid_ads,retail,employed,NA,54963.0,1,0,0.13,0
3,social_media,retail,self_employed,NA,26237.0,1,5,0.46,0
4,organic_search,retail,student,north_america,21992.0,3,6,0.70,1
...,...,...,...,...,...,...,...,...,...
3995,paid_ads,manufacturing,NA,north_america,66121.0,1,1,0.20,0
3996,paid_ads,manufacturing,employed,north_america,60720.0,4,6,0.69,1
3997,NA,manufacturing,NA,NA,49820.0,2,3,0.44,0
3998,organic_search,manufacturing,self_employed,north_america,52228.0,3,5,0.50,0
3999,paid_ads,retail,employed,asia,25824.0,1,4,0.41,0

In [104]:
df_full_train.converted.value_counts(normalize=True)

converted
1    0.57875
0    0.42125
Name: proportion, dtype: float64

In [105]:
df.industry.mode()
# Ques : 1

0    technology
Name: industry, dtype: str

In [106]:
df.industry.value_counts()

industry
technology       1173
retail            925
healthcare        840
finance           720
education         639
manufacturing     463
NA                240
Name: count, dtype: int64

In [107]:
cols = df.columns[(df.dtypes != 'str') & (df.columns != 'converted')]
corr_matrix = pd.DataFrame({
    c : df[cols].corrwith(df[c])
    for c in cols
}
)

corr_matrix

,annual_income,number_of_courses_viewed,interaction_count,lead_score
annual_income,1.000000,0.161300,0.122842,0.229496
number_of_courses_viewed,0.161300,1.000000,0.721609,0.757204
interaction_count,0.122842,0.721609,1.000000,0.915746
lead_score,0.229496,0.757204,0.915746,1.000000

In [108]:
corr_pairs = corr_matrix.unstack()

corr_pairs = corr_pairs[corr_pairs.index.get_level_values(0) != corr_pairs.index.get_level_values(1)]
corr_pairs = corr_pairs.drop_duplicates()

sorted_corr_pairs = corr_pairs.sort_values(ascending = False)
print(sorted_corr_pairs)

# Ques : 2

interaction_count         lead_score                  0.915746
lead_score                number_of_courses_viewed    0.757204
number_of_courses_viewed  lead_score                  0.757204
                          interaction_count           0.721609
lead_score                annual_income               0.229496
annual_income             lead_score                  0.229496
                          number_of_courses_viewed    0.161300
                          interaction_count           0.122842
dtype: float64

In [109]:
from sklearn.metrics import mutual_info_score

In [110]:
mutual_info = pd.DataFrame({
    'feature' : categorical,
    'mi_score' : [mutual_info_score(df_full_train[c], df_full_train['converted']) for c in categorical]
})

mutual_info.sort_values(by='mi_score', ascending=False).round({'mi_score': 2})
# max(mutual_info.sort_values(by='mi_score', ascending=False).round({'mi_score': 2})['mi_score'])
# Ques : 3

             feature  mi_score
0        lead_source      0.03
2  employment_status      0.02
1           industry      0.00
3           location      0.00

In [111]:
# although I am not required to use diff and risk ratio for now, but still can use it

global_converted = df_full_train['converted'].mean()

from IPython.display import display

for c in categorical:
    print(c)
    df_group = df_full_train.groupby(c).converted.agg(['mean', 'count'])
    df_group['diff'] = df_group['mean'] - global_converted
    df_group['risk_ratio'] = df_group['mean']/global_converted

    display(df_group)
    print()
    print()

lead_source

                    mean  count      diff  risk_ratio
lead_source
NA              0.579832    119  0.001082    1.001869
events          0.421782    505 -0.156968    0.728781
organic_search  0.679074    994  0.100324    1.173347
paid_ads        0.434879    906 -0.143871    0.751410
referral        0.767145    627  0.188395    1.325521
social_media    0.568905    849 -0.009845    0.982988

industry

                   mean  count      diff  risk_ratio
industry
NA             0.600000    200  0.021250    1.036717
education      0.520161    496 -0.058589    0.898767
finance        0.595782    569  0.017032    1.029429
healthcare     0.562784    661 -0.015966    0.972412
manufacturing  0.567639    377 -0.011111    0.980802
retail         0.556604    742 -0.022146    0.961734
technology     0.627225    955  0.048475    1.083758

employment_status

                       mean  count      diff  risk_ratio
employment_status
NA                 0.602564    156  0.023814    1.041147
employed           0.666351   2113  0.087601    1.151363
self_employed      0.553603    569 -0.025147    0.956549
student            0.434564    596 -0.144186    0.750866
unemployed         0.422261    566 -0.156489    0.729609

location

                   mean  count      diff  risk_ratio
location
NA             0.562874    167 -0.015876    0.972569
africa         0.534527    391 -0.044223    0.923589
asia           0.601907    839  0.023157    1.040012
europe         0.600221    903  0.021471    1.037100
north_america  0.579817   1090  0.001067    1.001843
south_america  0.545902    610 -0.032848    0.943243

In [167]:
from sklearn.feature_extraction import DictVectorizer

numerical = list(df.columns[df.dtypes != 'str'])
df[numerical] = df[numerical].fillna(0)

numerical = [c for c in numerical if c != 'converted']

dv = DictVectorizer(sparse=False)
train_dict = df_train[categorical + numerical].to_dict(orient = 'records')

X_train = dv.fit(train_dict)
X_train

DictVectorizer(sparse=False)

In [168]:
X_train = dv.transform(train_dict)
X_train

array([[8.0198e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        5.0000e+00],
       [5.0548e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+00],
       [7.6300e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       ...,
       [2.1561e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [3.1691e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 1.0000e+00,
        3.0000e+00],
       [4.6342e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        5.0000e+00]], shape=(3000, 28))

In [169]:
val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)
X_val

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 1.0000e+00,
        1.0000e+00],
       [6.3357e+04, 0.0000e+00, 1.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        4.0000e+00],
       [7.2351e+04, 0.0000e+00, 1.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        2.0000e+00],
       ...,
       [5.1328e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 1.0000e+00,
        3.0000e+00],
       [1.3315e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        3.0000e+00],
       [5.3098e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00]], shape=(1000, 28))

In [170]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver = 'liblinear', C = 1.0, max_iter = 1000, random_state = 42)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [171]:
model.intercept_[0]

np.float64(-0.09288149430633613)

In [172]:
model.coef_[0].round(2)

array([-0.  , -0.  ,  0.03, -0.02, -0.06, -0.05, -0.  , -0.03, -0.01,
       -0.02, -0.01, -0.03,  0.01,  0.25,  0.02, -0.  , -0.04,  0.01,
       -0.07,  0.03, -0.03, -0.  , -0.02, -0.01, -0.01, -0.02, -0.02,
        0.1 ])

In [173]:
y_pred = model.predict_proba(X_val)
y_pred

array([[0.45527705, 0.54472295],
       [0.20994793, 0.79005207],
       [0.49022091, 0.50977909],
       ...,
       [0.24221383, 0.75778617],
       [0.22098616, 0.77901384],
       [0.59553438, 0.40446562]], shape=(1000, 2))

In [174]:
y_pred = y_pred[:, 1]
y_pred

array([0.54472295, 0.79005207, 0.50977909, 0.52913949, 0.82072027,
       0.54246   , 0.50178717, 0.54698398, 0.82553299, 0.40583754,
       0.91301567, 0.33581825, 0.30789883, 0.42704803, 0.6219229 ,
       0.53665458, 0.41931937, 0.84087345, 0.79969125, 0.61790114,
       0.61625181, 0.68059931, 0.85605897, 0.8078487 , 0.62046017,
       0.45970722, 0.54556724, 0.41221393, 0.72714023, 0.46812079,
       0.77222191, 0.79043883, 0.61433884, 0.78549759, 0.49753426,
       0.66077291, 0.69804763, 0.76896543, 0.65657501, 0.64127911,
       0.66509115, 0.57942826, 0.67830946, 0.61186114, 0.86890227,
       0.4146967 , 0.84130129, 0.74229365, 0.68028539, 0.7189143 ,
       0.86417929, 0.64043375, 0.5424699 , 0.70225152, 0.27894903,
       0.70826494, 0.62310718, 0.47781771, 0.37914032, 0.69936035,
       0.52032869, 0.69977698, 0.75148939, 0.58087503, 0.47001802,
       0.56863492, 0.91297185, 0.79972028, 0.82206546, 0.36140197,
       0.66132404, 0.52330065, 0.79295471, 0.72068083, 0.71234212,
       0.64595334, 0.92090363, 0.82174666, 0.72939868, 0.68060557,
       0.4556843 , 0.76041067, 0.59946674, 0.82279814, 0.59782308,
       0.62356812, 0.34591823, 0.77925346, 0.84520512, 0.59397898,
       0.44218336, 0.76149021, 0.66593489, 0.75201767, 0.80214811,
       0.72858838, 0.7916209 , 0.67180861, 0.6875128 , 0.45740478,
       0.52167793, 0.45659876, 0.62894035, 0.63140961, 0.61152781,
       0.52812014, 0.78705487, 0.63881485, 0.76258233, 0.75352883,
       0.63996599, 0.33981211, 0.76306985, 0.53141787, 0.73832958,
       0.43311975, 0.70349024, 0.41560423, 0.8747922 , 0.83026729,
       0.74034795, 0.78829634, 0.64676151, 0.68564201, 0.37078883,
       0.90416256, 0.44986163, 0.73884813, 0.70480542, 0.89899102,
       0.60064396, 0.51090914, 0.69643018, 0.74276116, 0.65195044,
       0.69692341, 0.57675325, 0.63051928, 0.50090943, 0.70327756,
       0.8974762 , 0.82782707, 0.82016192, 0.59145964, 0.8070327 ,
       0.74306917, 0.41072349, 0.72853937, 0.89082389, 0.74514791,
       0.62288786, 0.60717542, 0.74197324, 0.85643585, 0.84343494,
       0.67068904, 0.30597789, 0.6641037 , 0.55588907, 0.79076372,
       0.5551314 , 0.67043142, 0.55393126, 0.56756437, 0.44529474,
       0.73893223, 0.32188436, 0.47761648, 0.70273436, 0.5992857 ,
       0.60267223, 0.74462361, 0.44305601, 0.65894503, 0.72616227,
       0.68854947, 0.53690286, 0.79551026, 0.83115284, 0.73983932,
       0.865709  , 0.51311179, 0.81622137, 0.58407707, 0.68381616,
       0.71556001, 0.70349311, 0.88643802, 0.71182954, 0.57211609,
       0.45567464, 0.70461834, 0.60587501, 0.5285453 , 0.57092886,
       0.74339965, 0.70591332, 0.43294865, 0.39579225, 0.7477749 ,
       0.30432088, 0.3972342 , 0.78595399, 0.61213508, 0.68234558,
       0.74238937, 0.61895155, 0.64512002, 0.70936502, 0.67085578,
       0.90186201, 0.93093534, 0.83998536, 0.77460868, 0.34263731,
       0.3674586 , 0.45639645, 0.5952988 , 0.67999529, 0.47279045,
       0.53999833, 0.54245699, 0.71910717, 0.46529573, 0.6420695 ,
       0.79285647, 0.5849115 , 0.60995549, 0.36648645, 0.50205982,
       0.75455872, 0.44741832, 0.40644882, 0.73338343, 0.53115803,
       0.75758826, 0.40491641, 0.83262036, 0.89866174, 0.69365872,
       0.79881422, 0.52647404, 0.6432329 , 0.7105723 , 0.69798973,
       0.60251613, 0.65179022, 0.71919128, 0.87156377, 0.82865756,
       0.64712578, 0.60819864, 0.51424614, 0.67094908, 0.50011651,
       0.84531405, 0.71031097, 0.64183052, 0.58356732, 0.65271409,
       0.74872668, 0.59762162, 0.90294928, 0.54896801, 0.57754359,
       0.81943893, 0.81093999, 0.36469025, 0.87633541, 0.69602586,
       0.65585024, 0.2698266 , 0.65262734, 0.93016241, 0.4558929 ,
       0.48728055, 0.59551634, 0.3314741 , 0.78326293, 0.68699653,
       0.96726562, 0.8413488 , 0.58649716, 0.69891447, 0.7917033 ,
       0.37286378, 0.8322252 , 0.70299236, 0.7986426 , 0.7690363 ,
       0.47473502, 0.6523271 , 0.84140362, 0.52005073, 0.55384984,
       0.7138704 , 0.49450125, 0.27082122, 0.53890056, 0.66224628,
       0.44278797, 0.8335098 , 0.33509714, 0.5049275 , 0.63407407,
       0.67170387, 0.89842254, 0.58674156, 0.75744975, 0.5488073 ,
       0.46707862, 0.72706399, 0.48074537, 0.65540678, 0.61648601,
       0.46009579, 0.40505733, 0.7911422 , 0.52606249, 0.68295515,
       0.70886129, 0.8345536 , 0.48238716, 0.49849194, 0.77172087,
       0.66090056, 0.68779792, 0.79588436, 0.5623885 , 0.76448984,
       0.68717446, 0.80450997, 0.76097582, 0.72524583, 0.87766422,
       0.58409454, 0.84578043, 0.31116805, 0.55550379, 0.62461071,
       0.70950467, 0.9312792 , 0.74332006, 0.51456018, 0.40340218,
       0.62960511, 0.53730428, 0.52934534, 0.56396305, 0.76737851,
       0.73126522, 0.50477779, 0.52510536, 0.4444034 , 0.50687953,
       0.56931602, 0.91205127, 0.38499453, 0.88521519, 0.74239772,
       0.68836872, 0.39832884, 0.77260236, 0.80686364, 0.65750702,
       0.68458052, 0.80400403, 0.72999847, 0.57103624, 0.81160612,
       0.59144263, 0.70815318, 0.89803138, 0.38484228, 0.50009244,
       0.59980879, 0.42355392, 0.59035451, 0.64072964, 0.74086665,
       0.69544062, 0.3904991 , 0.44631862, 0.71752399, 0.62473616,
       0.59495231, 0.68942016, 0.66175218, 0.73689657, 0.80439169,
       0.86759251, 0.66088211, 0.45060101, 0.79435599, 0.78113535,
       0.68823748, 0.77200575, 0.74098233, 0.52276915, 0.73128901,
       0.79242015, 0.84306672, 0.76028944, 0.65924179, 0.63575056,
       0.53965628, 0.56383444, 0.83605   , 0.64751013, 0.46761989,
       0.71486716, 0.56262902, 0.70108178, 0.85924945, 0.27102755,
       0.6133308 , 0.71238029, 0.30993289, 0.59836257, 0.54256343,
       0.51662587, 0.45617449, 0.26853457, 0.68839501, 0.85931897,
       0.51690035, 0.69174198, 0.39017309, 0.61280481, 0.58159411,
       0.62523117, 0.44439015, 0.76372413, 0.60730209, 0.83737267,
       0.41217822, 0.36564794, 0.64625012, 0.88260664, 0.55332378,
       0.76151843, 0.63263688, 0.80918488, 0.73001561, 0.62586399,
       0.7343078 , 0.85030709, 0.70916066, 0.50090501, 0.63615965,
       0.32567986, 0.74468515, 0.60195794, 0.82448914, 0.30071031,
       0.68853634, 0.30146298, 0.64905012, 0.40284546, 0.81007275,
       0.70057542, 0.36309233, 0.53363046, 0.68085135, 0.75900602,
       0.69453998, 0.6734509 , 0.38797328, 0.63062333, 0.76510983,
       0.57295665, 0.7486309 , 0.83861881, 0.42374791, 0.75186099,
       0.70965792, 0.73269827, 0.37888207, 0.57399334, 0.8520542 ,
       0.87023388, 0.49524384, 0.65343835, 0.62602007, 0.69085481,
       0.88704688, 0.65447964, 0.84463273, 0.67862835, 0.732379  ,
       0.89332488, 0.63218203, 0.71872022, 0.84760582, 0.52753662,
       0.85797509, 0.49846872, 0.78643089, 0.61411265, 0.90368555,
       0.79671354, 0.27404613, 0.87419439, 0.73227077, 0.60965876,
       0.81795788, 0.68821737, 0.51320805, 0.57933706, 0.83148008,
       0.82927704, 0.66846522, 0.66563728, 0.55477136, 0.39782461,
       0.68634414, 0.3691915 , 0.61932594, 0.62348799, 0.39575544,
       0.86209737, 0.77299553, 0.53787963, 0.5013931 , 0.71237776,
       0.3395799 , 0.66127218, 0.87086493, 0.69251681, 0.60357369,
       0.84379574, 0.79750386, 0.72208228, 0.73654891, 0.83766887,
       0.41877548, 0.63592806, 0.78841052, 0.68198821, 0.74430041,
       0.43835601, 0.58186737, 0.79489862, 0.9507383 , 0.36252467,
       0.4829667 , 0.75586986, 0.68939286, 0.25542963, 0.87543032,
       0.88868133, 0.31941619, 0.81186618, 0.57979994, 0.6627842 ,
       0.86244124, 0.49452393, 0.63916755, 0.6711093 , 0.80778263,
       0.56139194, 0.7280988 , 0.69632291, 0.60713156, 0.72080908,
       0.66336869, 0.45522184, 0.68055283, 0.84716067, 0.84681381,
       0.31192141, 0.61438675, 0.27484846, 0.82430013, 0.5938687 ,
       0.78510462, 0.42442315, 0.47030111, 0.55760549, 0.77493319,
       0.6646101 , 0.61814789, 0.4460791 , 0.66845082, 0.76736425,
       0.86272551, 0.64616675, 0.48287553, 0.58512365, 0.42404202,
       0.46874504, 0.47995206, 0.52035014, 0.60689544, 0.64497378,
       0.80584178, 0.57909062, 0.82621214, 0.59224584, 0.44082228,
       0.78783397, 0.75367426, 0.55440371, 0.50424327, 0.55734613,
       0.89675043, 0.51651844, 0.83180529, 0.50418882, 0.53543036,
       0.77749652, 0.45630461, 0.72994153, 0.59599101, 0.61777308,
       0.35405941, 0.63904918, 0.62594456, 0.74025559, 0.7353062 ,
       0.57274795, 0.53825426, 0.60882225, 0.4468115 , 0.70461549,
       0.75395272, 0.3606919 , 0.64812441, 0.72460889, 0.64964277,
       0.67856967, 0.73946172, 0.35708081, 0.7469964 , 0.63559271,
       0.44912186, 0.67634972, 0.56752226, 0.66568607, 0.5577915 ,
       0.76561179, 0.79782191, 0.50582059, 0.64186628, 0.75922736,
       0.61689001, 0.65607642, 0.30524058, 0.61832566, 0.83838058,
       0.70890719, 0.82935251, 0.61417759, 0.6251548 , 0.64637191,
       0.49117667, 0.6624936 , 0.46656072, 0.62328256, 0.81810232,
       0.81078728, 0.63169051, 0.50323369, 0.68223593, 0.42094443,
       0.68639475, 0.82212164, 0.69706922, 0.74294365, 0.6746901 ,
       0.50965758, 0.70643396, 0.72982205, 0.29445878, 0.71042677,
       0.52485409, 0.54678815, 0.56973868, 0.39870616, 0.54836616,
       0.92699041, 0.56245924, 0.57303337, 0.86345307, 0.57451458,
       0.67518117, 0.75106792, 0.67070159, 0.85731224, 0.43424904,
       0.65951351, 0.81602444, 0.78985135, 0.43612498, 0.67401921,
       0.61049945, 0.70318581, 0.61156912, 0.43669924, 0.57228912,
       0.80004869, 0.65001106, 0.33097584, 0.6111119 , 0.66932013,
       0.61868442, 0.58140323, 0.68071623, 0.57632862, 0.64335075,
       0.48765023, 0.4258213 , 0.62009371, 0.65282346, 0.688186  ,
       0.44469118, 0.73561894, 0.51467704, 0.55858613, 0.53116939,
       0.6576707 , 0.67672938, 0.49484459, 0.54416874, 0.48918544,
       0.76938493, 0.80175518, 0.2751457 , 0.90227234, 0.45733865,
       0.52894326, 0.82369058, 0.71744697, 0.78556927, 0.45001613,
       0.73389036, 0.40399858, 0.61986072, 0.85362328, 0.76449935,
       0.66324102, 0.46713866, 0.81045355, 0.74942515, 0.73754661,
       0.64938262, 0.81529182, 0.65856509, 0.78828273, 0.68473766,
       0.81751536, 0.73581373, 0.8585453 , 0.59777164, 0.80365943,
       0.6717288 , 0.90051601, 0.73757932, 0.62668202, 0.83794263,
       0.90293095, 0.55132565, 0.73868785, 0.6330455 , 0.44853599,
       0.73502446, 0.54954365, 0.50977211, 0.78423451, 0.66694156,
       0.29433219, 0.73044611, 0.57289494, 0.7356276 , 0.57286401,
       0.77779365, 0.48798234, 0.45354317, 0.60513415, 0.6915549 ,
       0.74851501, 0.5314805 , 0.83487845, 0.56000826, 0.74369751,
       0.62894393, 0.39997234, 0.84635784, 0.94772485, 0.42488017,
       0.63216759, 0.64818659, 0.65121407, 0.74909789, 0.70215423,
       0.89864404, 0.88717781, 0.61594616, 0.77696251, 0.50837172,
       0.70750915, 0.30579538, 0.67542435, 0.79039221, 0.72172809,
       0.72494309, 0.60752342, 0.69982127, 0.69573164, 0.52596444,
       0.70209501, 0.64088569, 0.56354722, 0.44296288, 0.86519616,
       0.59105933, 0.70050181, 0.67651822, 0.84766637, 0.61713167,
       0.78571593, 0.65936313, 0.48628171, 0.85502498, 0.68883799,
       0.58700711, 0.64738152, 0.84975627, 0.72997296, 0.47220156,
       0.7222461 , 0.80556616, 0.63255758, 0.5012614 , 0.47004393,
       0.40449008, 0.65771956, 0.52718901, 0.55585843, 0.77127627,
       0.46095315, 0.70521201, 0.67351305, 0.57391309, 0.67090491,
       0.63715272, 0.6974557 , 0.43417751, 0.76460882, 0.74420227,
       0.83375757, 0.61567927, 0.78490862, 0.75318299, 0.38290628,
       0.63722857, 0.6951215 , 0.40492963, 0.80271108, 0.71772153,
       0.57045458, 0.64748024, 0.83744492, 0.79418513, 0.69185211,
       0.92164861, 0.40158519, 0.68338462, 0.69830172, 0.42886168,
       0.5529115 , 0.7733174 , 0.45922049, 0.76483567, 0.55605473,
       0.69179276, 0.85478879, 0.64703144, 0.85705787, 0.57965551,
       0.78410728, 0.82401531, 0.54743182, 0.64521126, 0.51545093,
       0.71563647, 0.65961368, 0.49108682, 0.74070746, 0.61720526,
       0.74726413, 0.5444032 , 0.53876702, 0.76681002, 0.67150388,
       0.75842305, 0.61868053, 0.85302547, 0.75785512, 0.81962947,
       0.52552979, 0.49482154, 0.54346151, 0.59081385, 0.75773441,
       0.66357886, 0.56614451, 0.78797801, 0.38003532, 0.73361302,
       0.46871679, 0.81656924, 0.4132209 , 0.77042069, 0.42782417,
       0.64753804, 0.66968493, 0.63883109, 0.70099114, 0.51142395,
       0.71472982, 0.5909093 , 0.81818358, 0.71741694, 0.62828631,
       0.52966933, 0.80072907, 0.66934516, 0.7349264 , 0.69937514,
       0.68073805, 0.77262396, 0.55546986, 0.7574736 , 0.72498545,
       0.83677145, 0.79590286, 0.66218556, 0.81920699, 0.68351642,
       0.8593145 , 0.86824827, 0.62226093, 0.50333026, 0.65788398,
       0.47272464, 0.46997323, 0.54740162, 0.85730479, 0.39237208,
       0.69921092, 0.71672492, 0.85571761, 0.58180271, 0.84711846,
       0.56705096, 0.35561705, 0.72524746, 0.70331147, 0.6864242 ,
       0.82781914, 0.60811778, 0.90007644, 0.67640321, 0.56712951,
       0.73638251, 0.33515378, 0.6763755 , 0.43480068, 0.58148587,
       0.48398889, 0.82276403, 0.70017081, 0.54794546, 0.62626086,
       0.7265353 , 0.52891483, 0.80955076, 0.80967738, 0.70682331,
       0.64211908, 0.70347825, 0.83785165, 0.81805312, 0.54291817,
       0.50423611, 0.58086184, 0.72697062, 0.54984415, 0.49685288,
       0.36228441, 0.76366489, 0.64263014, 0.58862881, 0.79765063,
       0.74184825, 0.65703283, 0.75778617, 0.77901384, 0.40446562])

In [175]:
contract_pred = (y_pred >= 0.5)
    
print("Model accuracy:", (y_val == contract_pred).mean())

print("Baseline accuracy:", max(y_val.mean(), 1 - y_val.mean()))

# Ques : 4

Model accuracy: 0.651
Baseline accuracy: 0.586

In [176]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_val, contract_pred))
print(classification_report(y_val, contract_pred))

[[120 294]
 [ 55 531]]
              precision    recall  f1-score   support

           0       0.69      0.29      0.41       414
           1       0.64      0.91      0.75       586

    accuracy                           0.65      1000
   macro avg       0.66      0.60      0.58      1000
weighted avg       0.66      0.65      0.61      1000

In [177]:
df_pred = pd.DataFrame()
df_pred['probability'] = y_pred
df_pred['prediction'] = contract_pred.astype(int)
df_pred['actual'] = y_val
df_pred['correct'] = (y_val == contract_pred).astype(int)

df_pred.head()

   probability  prediction  actual  correct
0     0.544723           1       0        0
1     0.790052           1       1        1
2     0.509779           1       1        1
3     0.529139           1       1        1
4     0.820720           1       0        0

In [180]:
features = categorical + numerical

original_accuracy = (y_val == contract_pred).mean()

results = {}

for feat in features:
    updated_features = [f for f in features if f != feat]
    train_dict = df_train[updated_features].to_dict(orient='records')
    X_train_new = dv.fit_transform(train_dict)

    model.fit(X_train_new, y_train)

    val_dict = df_val[updated_features].to_dict(orient='records')
    X_val_new = dv.transform(val_dict)
    
    y_pred_new = model.predict_proba(X_val_new)[:, 1]

    accuracy = ((y_pred_new >= 0.5) == y_val).mean()

    results[feat] = {
        'accuracy' : accuracy,
        'difference' : abs(original_accuracy - accuracy)
    }
pd.DataFrame(results).T.sort_values(by = 'difference')

# Ques : 5

                          accuracy  difference
industry                     0.651       0.000
lead_score                   0.651       0.000
location                     0.650       0.001
lead_source                  0.648       0.003
employment_status            0.648       0.003
number_of_courses_viewed     0.645       0.006
interaction_count            0.593       0.058
annual_income                0.716       0.065

In [183]:
C_val = [0.000001, 0.00001, 0.0001, 0.001]
C_best = C_val[0]

accuracy_val = float('-inf')
result = {}

train_dict = df_train[features].to_dict(orient='records')
val_dict = df_val[features].to_dict(orient='records')

X_train = dv.fit_transform(train_dict)
X_val = dv.transform(val_dict)

for c in C_val:
    model = LogisticRegression(
        solver='liblinear', C=c, max_iter=1000, random_state=42
    )

    model.fit(X_train, y_train)

    y_pred_new_c = model.predict_proba(X_val)[:, 1]

    accuracy = round(((y_pred_new_c >= 0.5) == y_val).mean(), 3)

    result[c] = {
        'C': c,
        'accuracy': accuracy
    }

    if accuracy > accuracy_val:
        C_best = c
        accuracy_val = accuracy

display(pd.DataFrame(result).T.sort_values(by='accuracy', ascending=False))

print("Best C:", C_best)
print("Best accuracy:", accuracy_val)

# Ques : 6

                 C  accuracy
0.001000  0.001000     0.648
0.000001  0.000001     0.590
0.000010  0.000010     0.590
0.000100  0.000100     0.590

Best C: 0.001
Best accuracy: 0.648